env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - 0
    - double
  semi:
    - error
    - never
