extends: airbnb
env: 
  browser: true
  node: true
  jquery: true
plugins:
  - react
rules:
  semi: 
    - 2
    - never
  no-unused-expressions:
    - 2  
    - allowTernary: true
  one-var:
    - 2
    - uninitialized: always
  one-var-declaration-per-line:
    - 0
  brace-style:
    - 2
    - stroustrup
  
